---
title: "Khyati and Gabe"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r loading-libraries, message=F}
library(flexdashboard)
library(devtools)
library(tidyverse)
library(gganimate)
library(gifski)
library(png)
library(here)
library(lemon)
library(RColorBrewer)
library(scales)
library(janitor)
library(ggrepel)
library(ggvoronoi)
# library(ggtext)
library(rvest)
library(fuzzyjoin)
#library(jkmisc)
library(ragg)
library(plotly)
```


```{r import-dataset, message=FALSE}
park_visits <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/national_parks.csv")
state_pop <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/state_pop.csv")
gas_price <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/gas_price.csv")
park_locations <- read_csv("data/NationalParksLatLong.csv")
```

### Park Locations


Plotting the locations of the various national parks

```{r most-popular-national-park-locations}

library(sp)
library(leaflet)
coordinates(park_locations) <- ~Longitude+Latitude
leaflet(park_locations) %>% addMarkers() %>% addTiles()
```

*** 

Source: https://github.com/spren9er/tidytuesday/blob/master/tidytuesday_201938_national_park_visits.r
Improvments seen below are discussed here: https://evancanfield.netlify.com/posts/2019-09-16-national-parks-tidytuesday/tidy-tuesday-38/


### Park change year over year

```{r}
pv_ch <- park_visits %>% 
  distinct(year, unit_name, unit_type, visitors) %>% 
  filter(unit_type == "National Park" & year != "Total") %>%
  mutate(year = as.numeric(year)) %>% 
  group_by(unit_name) %>% 
  arrange(year, .by_group = TRUE) %>%
  mutate(yoy = visitors - lag(visitors)) %>% 
  filter(unit_name != "Denali National Preserve")
  
 
pv_ch %>%
  ggplot() +
  geom_line(aes(x = year, y = yoy, group = unit_name), size = 0.2) +
  scale_x_continuous(breaks = seq(1910, 2010, 10), expand = expand_scale(add = c(5, 1))) +
  scale_y_continuous(breaks = c(-3000000, 0, 1000000), labels = paste0(c(-3000000, 0, 1000000)/1000000, "M")) +
  facet_wrap(vars(unit_name), ncol = 3) +
  labs(
    title = "National Park Visits 1904–2016",
    subtitle = "Year-over-year change in total visits by park",
    caption = "Source: dataisplural/data.world | Graphic: Georgios Karamanis"
  ) +
  theme_void(base_family = "Times New Roman") +
  theme(
    legend.position = "none",
    legend.title = element_text(size = 20, color = "grey20"),
    legend.margin = margin(0, 0, 20, 0),
    plot.background = element_rect(fill = "grey80", color = NA),
    strip.background = element_rect(fill = "grey80", color = NA),
    strip.text = element_text(family = "Times New Roman", color = "grey30",
                               hjust = 1, vjust = 1),
    plot.title = element_text(size = 28, color = "grey20", family = "Times New Roman"),
    plot.subtitle = element_text(size = 20, color = "grey20", margin = margin(5, 0, 30, 0)),
    plot.caption = element_text(size = 8, color = "grey30", margin = margin(20, 0, 0, 0)),
    axis.text.x = element_text(family = "Times New Roman", size = 7, color = "grey40"),
    axis.text.y = element_text(family = "Times New Roman", size = 7, color = "grey40"),
    panel.grid.major.x = element_line(color = "grey75"),
    panel.grid.major.y = element_line(color = "grey75"),
    plot.margin = margin(20, 20, 20, 20)
  )
```

*** 

Commentary for park viz 2.
